import { BlockDefinition } from "@/types/blocks";

export const BLOCK_REGISTRY: BlockDefinition[] = [
  {
    type: "input",
    category: "io",
    label: "Input",
    color: "#22c55e",
    inputs: [],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [
      { key: "shape", label: "Shape", type: "tuple", default: [1, 28, 28] },
    ],
    defaultParams: { shape: [1, 28, 28] },
  },
  {
    type: "output",
    category: "io",
    label: "Output",
    color: "#ef4444",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [],
    parameters: [
      {
        key: "loss_fn",
        label: "Loss Function",
        type: "select",
        options: ["CrossEntropyLoss", "MSELoss", "BCEWithLogitsLoss"],
        default: "CrossEntropyLoss",
      },
      {
        key: "num_classes",
        label: "Num Classes",
        type: "number",
        min: 1,
        default: 10,
      },
    ],
    defaultParams: { loss_fn: "CrossEntropyLoss", num_classes: 10 },
  },
  {
    type: "linear",
    category: "layer",
    label: "Linear",
    color: "#3b82f6",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [
      {
        key: "out_features",
        label: "Output Features",
        type: "number",
        min: 1,
        default: 128,
      },
      { key: "bias", label: "Bias", type: "boolean", default: true },
    ],
    defaultParams: { out_features: 128, bias: true },
  },
  {
    type: "conv2d",
    category: "layer",
    label: "Conv2d",
    color: "#3b82f6",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [
      {
        key: "out_channels",
        label: "Output Channels",
        type: "number",
        min: 1,
        default: 32,
      },
      {
        key: "kernel_size",
        label: "Kernel Size",
        type: "number",
        min: 1,
        default: 3,
      },
      {
        key: "stride",
        label: "Stride",
        type: "number",
        min: 1,
        default: 1,
      },
      {
        key: "padding",
        label: "Padding",
        type: "number",
        min: 0,
        default: 0,
      },
    ],
    defaultParams: { out_channels: 32, kernel_size: 3, stride: 1, padding: 0 },
  },
  {
    type: "relu",
    category: "activation",
    label: "ReLU",
    color: "#f59e0b",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [],
    defaultParams: {},
  },
  {
    type: "gelu",
    category: "activation",
    label: "GELU",
    color: "#f59e0b",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [],
    defaultParams: {},
  },
  {
    type: "sigmoid",
    category: "activation",
    label: "Sigmoid",
    color: "#f59e0b",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [],
    defaultParams: {},
  },
  {
    type: "batchnorm",
    category: "normalization",
    label: "BatchNorm",
    color: "#8b5cf6",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [],
    defaultParams: {},
  },
  {
    type: "layernorm",
    category: "normalization",
    label: "LayerNorm",
    color: "#8b5cf6",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [],
    defaultParams: {},
  },
  {
    type: "dropout",
    category: "regularization",
    label: "Dropout",
    color: "#ec4899",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [
      {
        key: "p",
        label: "Probability",
        type: "number",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.5,
      },
    ],
    defaultParams: { p: 0.5 },
  },
  {
    type: "maxpool2d",
    category: "pooling",
    label: "MaxPool2d",
    color: "#06b6d4",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [
      {
        key: "kernel_size",
        label: "Kernel Size",
        type: "number",
        min: 1,
        default: 2,
      },
      {
        key: "stride",
        label: "Stride",
        type: "number",
        min: 1,
        default: 2,
      },
    ],
    defaultParams: { kernel_size: 2, stride: 2 },
  },
  {
    type: "adaptiveavgpool2d",
    category: "pooling",
    label: "AdaptiveAvgPool2d",
    color: "#06b6d4",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [
      {
        key: "output_size",
        label: "Output Size",
        type: "tuple",
        default: [1, 1],
      },
    ],
    defaultParams: { output_size: [1, 1] },
  },
  {
    type: "flatten",
    category: "utility",
    label: "Flatten",
    color: "#6b7280",
    inputs: [{ id: "in", label: "Input" }],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [],
    defaultParams: {},
  },
  {
    type: "add",
    category: "merge",
    label: "Add",
    color: "#14b8a6",
    inputs: [
      { id: "in_a", label: "Input A" },
      { id: "in_b", label: "Input B" },
    ],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [],
    defaultParams: {},
  },
  {
    type: "concat",
    category: "merge",
    label: "Concat",
    color: "#14b8a6",
    inputs: [
      { id: "in_a", label: "Input A" },
      { id: "in_b", label: "Input B" },
    ],
    outputs: [{ id: "out", label: "Output" }],
    parameters: [
      { key: "dim", label: "Dimension", type: "number", min: 0, default: 1 },
    ],
    defaultParams: { dim: 1 },
  },
];

export function getBlockDef(type: string): BlockDefinition | undefined {
  return BLOCK_REGISTRY.find((b) => b.type === type);
}

export const BLOCK_CATEGORIES = [
  { key: "io", label: "Input / Output" },
  { key: "layer", label: "Layers" },
  { key: "activation", label: "Activations" },
  { key: "normalization", label: "Normalization" },
  { key: "regularization", label: "Regularization" },
  { key: "pooling", label: "Pooling" },
  { key: "merge", label: "Merge" },
  { key: "utility", label: "Utility" },
] as const;
